config/routes.rb
Scanner::Application.routes.draw do
  match 'about' => "pages#about"
  match 'player(/:stuff)' => "pages#player"

  resources :audios

  resources :cities

  resources :calls do
    get 'recent', :on => :collection
  end

  resources :groups

  root :to => 'pages#player'

end

app/models/call.rb
class Call < ActiveRecord::Base
  attr_accessible :end, :frequency, :start, :group_id, :audio_id
  belongs_to :group
  validates :start, :presence => true
  validates :end, :presence => true
  validates :end, :date => { :after => :start }
  validates :frequency, :presence => true
  validates :group_id,
            :numericality => { :only_integer => true,
                               :greater_than_or_equal_to => 0x0,
                               :less_than_or_equal_to => 0xFFFF },
                       :presence => true
  validates_associated :group
  has_one :audio

  def group_name
    return group ? group.name : "UNKNOWN"
  end

  def full_group_name
    return group ? group.full_name : "UNKNOWN"
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  # GET /calls
  # GET /calls.json
  def index
    @calls = Call.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @calls }
    end
  end

  # GET /calls/recent
  # GET /calls/recent.json
  def recent
    @calls = Call.where("audio_id IS NOT NULL").order("start ASC").limit(50).map do |call|
      { :id => call.id,
        :start => call.start,
        :end => call.end,
        :frequency => call.frequency,
        :group_full_name => call.group.full_name,
        :group_name => call.group.name }
    end
    
    respond_to do |format|
      format.html { render "index" }
      format.json { render json: @calls }
    end
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
    @call = Call.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @call }
      format.oga {
        if @call.audio
          send_file @call.audio.data.path, :type => @call.audio.data_content_type, :disposition => 'inline'
        else
          redirect_to :status => 404
        end
      }
    end
  end

  # GET /calls/new
  # GET /calls/new.json
  def new
    @call = Call.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @call }
    end
  end

  # GET /calls/1/edit
  def edit
    @call = Call.find(params[:id])
  end

  # POST /calls
  # POST /calls.json
  def create
    @audio = Audio.new(params[:audio])
    @call = Call.new(params[:call])
    @audio.call = @call
    @call.audio = @audio

    respond_to do |format|
      if @audio.save && @call.save
        format.html { redirect_to @call, notice: 'Call was successfully created.' }
        format.json { render json: @call, status: :created, location: @call }
      else
        format.html { render action: "new" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /calls/1
  # PUT /calls/1.json
  def update
    @call = Call.find(params[:id])

    respond_to do |format|
      if @call.update_attributes(params[:call])
        format.html { redirect_to @call, notice: 'Call was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call = Call.find(params[:id])
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_form.html.erb
<%= form_for(@call, :html => { :multipart => true }) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.datetime_select :end %>
  </div>
  <div class="field">
    <%= f.label :frequency %><br />
    <%= f.text_field :frequency %>
  </div>
  <div class="field">
    <%= f.label :group %><br/>
    <%= f.text_field :group_id %>
  </div>
  <div class="field">
    <%= fields_for 'audio' do |af| %>
      <%= af.label :audio %><br/>
      <%= af.file_field :data %>
    <% end %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', calls_path %>

app/views/calls/index.html.erb
<h1>Listing calls</h1>

<table>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th>Frequency</th>
    <th>Talkgroup</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calls.each do |call| %>
  <tr>
    <td><%= call.start %></td>
    <td><%= call.end %></td>
    <td><%= call.frequency %></td>
    <td><%= call.full_group_name %></td>
    <td><%= link_to 'Show', call %></td>
    <td><%= link_to 'Edit', edit_call_path(call) %></td>
    <td><%= link_to 'Destroy', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render 'form' %>

<%= link_to 'Back', calls_path %>

app/views/calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start:</b>
  <%= @call.start %>
</p>

<p>
  <b>End:</b>
  <%= @call.end %>
</p>

<p>
  <b>Frequency:</b>
  <%= @call.frequency %>
</p>

<p>
  <b>Talkgroup:</b>
  <%= @call.full_group_name %>
</p>

<% if @call.audio %>
<p>
  <%= link_to "Audio", call_path(@call, :format => :oga) %>
</p>
<% else %>
<p>
  <em>No Audio</em>
</p>
<% end %>

<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', calls_path %>